// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // @ts-expect-error directUrl added for Supabase session-mode DDL support
    directUrl: process.env["DIRECT_URL"],
  },
});
